### PR TITLE
Ping+shib fix

### PR DESCRIPTION
**Pull request by mrajashree**

### CODE REVIEW

**Comment by prachidamle** [comment]
@mrajashree we should also create a document 
1) to explain the steps to configure a PING IDP to work with ldap 
2) to explain the steps needed to configure Rancher SP with the IDP

**Comment by mrajashree** [comment]
https://github.com/rancher/rancher/issues/8140
https://github.com/rancher/rancher/issues/8665

**Comment by cjellick** [comment]
LGTM

**Comment by cjellick** [comment]
LGTM from @prachidamle as well (outside of updating the docs)

**Comment by prachidamle** [comment]
LGTM

**Pull request merged**
