### PR TITLE
disable cgo

### PR DESCRIPTION
**Pull request by cjellick**

### CODE REVIEW

**Comment by prachidamle** [comment]
Why the flag @cjellick ?

**Comment by cjellick** [comment]
@prachidamle this bug: https://github.com/rancher/rancher/issues/6111
I'm doing it for all projects

**Comment by ppandy** [comment]
@cjellick This is great! Nice catch. Any timeline on seeing this in a release candidate? I've just tried v1.5.0-rc1 and got the same error, so quietly hoping for rc2?

**Comment by cjellick** [comment]
@ppandy bad news! For this repo specifically, I had to revert the change because I discovered it broke stuff related to our SAML integration, which depends on packages that depend on packages that depend on some non-statically compiled libraries. 

Until we work that out, this won't make it in. It doesn't look like it'll make it into 1.5.0.

Here's the PR that reverted it, which has a little explanation:
https://github.com/rancher/rancher-auth-service/pull/9

**Comment by ppandy** [comment]
@cjellick Ah, bummer, but understood. I'm looking into what specifically is wrong with CGO on CentOS, maybe we can work it from the other direction...

**Pull request merged**
